### ISSUE TITLE
Road to Web3 - Connect APIs - performUpkeep Function Throws Error

### ISSUE THREAD

**Issue by matthewclickbid** [zeuslawyer/chainlink-dynamic-nft-alchemy#5]
New to Road to Web3 and stuck on lesson 5. After a full copy/paste of the contracts (originally thought issue was an error in my code) I still get the following error when running performUpkeep (with [] as param).

> transact to BullBear.performUpkeep errored: VM error: revert.
>
>revert
>	The transaction has been reverted to the initial state.
>Error provided by the contract:
>InvalidConsumer
>Parameters:
>{}
>Debug the transaction to get more information.

**Comment by matthewclickbid** [comment]
Just determined that a missing step is required between steps 4 and 5.
You must use the addConsumer() function with the new subscription ID and the Bull&Bear contract address.

**Comment by leonidkuznetsov18** [comment]
> Just determined that a missing step is required between steps 4 and 5. You must use the addConsumer() function with the new subscription ID and the Bull&Bear contract address.

I have the same issue, thanks for helping!
